### ISSUE TITLE
Option to buy pre-assembled units?

### ISSUE THREAD

**Issue by carstenschwede** [HiveTracker/HiveTracker.github.io#1]
Would be great if there are any options to order already pre-assembled units.

**Comment by honnet** [comment]
If you want to be notified when it happens, you can:
- follow us: [twitter.com/hive_tracker](https://twitter.com/hive_tracker)
- join the group: [groups.google.com/forum/#!forum/hivetracker](https://groups.google.com/forum/#!forum/hivetracker)

If you present your project and it's connected to some of ours, maybe we'll find a prototype for you ;)

**Comment by Bluscream** [comment]
That would be super awesome. I'll preorder 10 of them for MetrixVR fullbody
