### ISSUE TITLE
work as a out of the box vive tracker? Emulate one? Spoof as one?

### ISSUE THREAD

**Issue by Lhun** [HiveTracker/HiveTracker.github.io#2]
Hi there, 
I've been commenting on several projects and getting in touch with dozens of people in an effort to democratize vive trackers for social vr programs like vrchat, sine.space, high fidelity, etc. 
a 3 tracker system for full body tracking for purely entertainment purposes should not cost as much as a whole hmd setup, and vive trackers are too expensive. 
Myself and several thousand others feel the same, and that gave rise to kinecttovr and driver4vr as well as matzman666's openvr input emulator.

I guess what I'm trying to get at is it possible already or could you program these to act as vive trackers in openvr once connected to steamvr? 

and if so I'll buy hundreds.

**Comment by honnet** [comment]
Hey,
Thanks for your interest!
If you want to be notified when it is ready, you can:
- follow us: http://twitter.com/hive_tracker
- join the group: http://groups.google.com/forum/#!forum/hivetracker
- contact us: hivetracker+owners@googlegroups.com
